### ISSUE TITLE
Redirect when proxying failed

### ISSUE THREAD

**Issue by Tidyzq** [olalonde/follow-redirects#85] opened 2018-05-10 15:02 UTC
When redirect with proxying, an error will be throw:
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
Emitted 'error' event at:
    at Socket.socketErrorListener (_http_client.js:371:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:174:19)
```
Here is a minified code to reproduce the error:

```javascript
var http = require('http');
var followRedirect = require('follow-redirects').http
var url = require('url');

var str = 'test response', proxyStr = ' through proxy'

var server = http.createServer(function (req, res) {
  var parsed = url.parse(req.url);

  if (parsed.pathname === '/one') {
    res.setHeader('Location', '/two');
    res.statusCode = 302;
    res.end();
  } else {
    res.end(str);
  }
}).listen(4444, function () {

  var proxy = http.createServer(function (request, response) {
    var parsed = url.parse(request.url);
    var opts = {
      hostname: parsed.hostname,
      port: parsed.port,
      path: parsed.path
    };

    http.get(opts, function (res) {
      var body = '';
      res.on('data', function (data) {
        body += data;
      });
      res.on('end', function () {
        if (res.headers.location) {
          response.setHeader('Location', res.headers.location);
        }
        response.statusCode = res.statusCode;
        response.end(body + proxyStr);
      });
    });

  }).listen(4000, function () {

    followRedirect.get({
      protocol: 'http:',
      port: '4000',
      hostname: 'localhost',
      path: 'http://localhost:4444/one',
    }, function (response) {
        // response data should equals to `str + proxyStr`
    });

  });
});
```
Where `http://localhost:4444` represents the server with redirection, and `http://localhost:4000` represents the proxy server.

**Comment by Tidyzq** [comment] 2018-05-10 15:17
From my point of view, this error occurs because we use `this._currentUrl` to decide the redirect url, which is in the following line:
https://github.com/olalonde/follow-redirects/blob/1b6340f83ad5596a0a38c16a7113692bd90301f2/index.js#L205

Take my code for example, the `this._currentUrl` equals to `http://localhost:4000/http://localhost:4444/one`, and the `redirectUrl` will be `http://localhost:4000/two`. Then the proxy server will send a request to `http://localhost/two` (so the error message above is about my code rather than yours).

The expect behaviour is that the `this._options` after the first request to be like
```javascript
{
  protocol: 'http:',
  port: '4000',
  hostname: 'localhost',
  path: 'http://localhost:4444/two'
}
```

**Comment by RubenVerborgh** [comment] 2018-05-19 15:12
The issue is in your example code:

```javascript
    var parsed = url.parse(request.url);
    var opts = {
      hostname: parsed.hostname,
      port: parsed.port,
      path: parsed.path
    };
```

`request.url` is just [the relative URL from the HTTP request line](https://nodejs.org/api/http.html#http_message_url), so `/one` rather than a full URL.

Hence, `parsed.hostname` and `parsed.port` are `null`.

Which also makes sense, because the proxy server is the one who should know about the back-end server, not the client. Your code can be fixed by:

```javascript
    var parsed = url.parse(request.url);
    var opts = {
      hostname: 'localhost',
      port: 4444,
      path: parsed.path
    };
```

**Closed by RubenVerborgh** 2018-05-19 15:12 UTC
Labels: invalid
